export const usuarios = [
    {
        "codigo": 1,
        "primerNombre": "Juan",
        "segundoNombre": "Carlos",
        "primerApellido": "Pérez",
        "segundoApellido": "García",
        "cedula": "12345678",
        "correo": "juan.perez@example.com",
        "celular": "3001234567",
        "rol": "admin",
        "estado": "activo"
    },
    {
        "codigo": 2,
        "primerNombre": "María",
        "segundoNombre": "Luisa",
        "primerApellido": "Rodríguez",
        "segundoApellido": "López",
        "cedula": "23456789",
        "correo": "maria.rodriguez@example.com",
        "celular": "3102345678",
        "rol": "coordinador",
        "estado": "activo"
    },
    {
        "codigo": 3,
        "primerNombre": "Pedro",
        "segundoNombre": "José",
        "primerApellido": "Martínez",
        "segundoApellido": "Hernández",
        "cedula": "34567890",
        "correo": "pedro.martinez@example.com",
        "celular": "3203456789",
        "rol": "profesor",
        "estado": "activo"
    },
    {
        "codigo": 4,
        "primerNombre": "Ana",
        "segundoNombre": "María",
        "primerApellido": "Sánchez",
        "segundoApellido": "Ramírez",
        "cedula": "45678901",
        "correo": "ana.sanchez@example.com",
        "celular": "3304567890",
        "rol": "auxiliar",
        "estado": "activo"
    },
    {
        "codigo": 5,
        "primerNombre": "Luis",
        "segundoNombre": "Miguel",
        "primerApellido": "Gómez",
        "segundoApellido": "Vargas",
        "cedula": "56789012",
        "correo": "luis.gomez@example.com",
        "celular": "3405678901",
        "rol": "admin",
        "estado": "activo"
    },
    {
        "codigo": 6,
        "primerNombre": "Laura",
        "segundoNombre": "Isabel",
        "primerApellido": "Torres",
        "segundoApellido": "Díaz",
        "cedula": "67890123",
        "correo": "laura.torres@example.com",
        "celular": "3506789012",
        "rol": "coordinador",
        "estado": "activo"
    },
    {
        "codigo": 7,
        "primerNombre": "Carlos",
        "segundoNombre": "Andrés",
        "primerApellido": "Romero",
        "segundoApellido": "Pineda",
        "cedula": "78901234",
        "correo": "carlos.romero@example.com",
        "celular": "3607890123",
        "rol": "profesor",
        "estado": "activo"
    },
    {
        "codigo": 8,
        "primerNombre": "Marta",
        "segundoNombre": "Lucía",
        "primerApellido": "Rojas",
        "segundoApellido": "Suárez",
        "cedula": "89012345",
        "correo": "marta.rojas@example.com",
        "celular": "3708901234",
        "rol": "auxiliar",
        "estado": "activo"
    },
    {
        "codigo": 9,
        "primerNombre": "Fernando",
        "segundoNombre": "Alberto",
        "primerApellido": "Jiménez",
        "segundoApellido": "Navarro",
        "cedula": "90123456",
        "correo": "fernando.jimenez@example.com",
        "celular": "3809012345",
        "rol": "admin",
        "estado": "activo"
    },
    {
        "codigo": 10,
        "primerNombre": "Lucía",
        "segundoNombre": "Gabriela",
        "primerApellido": "Ruiz",
        "segundoApellido": "Cruz",
        "cedula": "01234567",
        "correo": "lucia.ruiz@example.com",
        "celular": "3900123456",
        "rol": "coordinador",
        "estado": "activo"
    },
    {
        "codigo": 11,
        "primerNombre": "Ricardo",
        "segundoNombre": "Antonio",
        "primerApellido": "Moreno",
        "segundoApellido": "Mendoza",
        "cedula": "11234567",
        "correo": "ricardo.moreno@example.com",
        "celular": "3101123456",
        "rol": "profesor",
        "estado": "activo"
    },
    {
        "codigo": 12,
        "primerNombre": "Paula",
        "segundoNombre": "Andrea",
        "primerApellido": "Ortiz",
        "segundoApellido": "Núñez",
        "cedula": "21234567",
        "correo": "paula.ortiz@example.com",
        "celular": "3202123456",
        "rol": "auxiliar",
        "estado": "activo"
    },
    {
        "codigo": 13,
        "primerNombre": "David",
        "segundoNombre": "Alejandro",
        "primerApellido": "Castro",
        "segundoApellido": "Salazar",
        "cedula": "31234567",
        "correo": "david.castro@example.com",
        "celular": "3303123456",
        "rol": "admin",
        "estado": "activo"
    },
    {
        "codigo": 14,
        "primerNombre": "Andrea",
        "segundoNombre": "Mariana",
        "primerApellido": "Vega",
        "segundoApellido": "Pérez",
        "cedula": "41234567",
        "correo": "andrea.vega@example.com",
        "celular": "3404123456",
        "rol": "coordinador",
        "estado": "activo"
    },
    {
        "codigo": 15,
        "primerNombre": "José",
        "segundoNombre": "Luis",
        "primerApellido": "Herrera",
        "segundoApellido": "González",
        "cedula": "51234567",
        "correo": "jose.herrera@example.com",
        "celular": "3505123456",
        "rol": "profesor",
        "estado": "activo"
    },
    {
        "codigo": 16,
        "primerNombre": "Claudia",
        "segundoNombre": "Patricia",
        "primerApellido": "Mora",
        "segundoApellido": "Rojas",
        "cedula": "61234567",
        "correo": "claudia.mora@example.com",
        "celular": "3606123456",
        "rol": "auxiliar",
        "estado": "activo"
    },
    {
        "codigo": 17,
        "primerNombre": "Francisco",
        "segundoNombre": "Javier",
        "primerApellido": "López",
        "segundoApellido": "Duarte",
        "cedula": "71234567",
        "correo": "francisco.lopez@example.com",
        "celular": "3707123456",
        "rol": "admin",
        "estado": "activo"
    },
    {
        "codigo": 18,
        "primerNombre": "Isabel",
        "segundoNombre": "Cristina",
        "primerApellido": "Navarro",
        "segundoApellido": "Guzmán",
        "cedula": "81234567",
        "correo": "isabel.navarro@example.com",
        "celular": "3808123456",
        "rol": "coordinador",
        "estado": "activo"
    },
    {
        "codigo": 19,
        "primerNombre": "Raúl",
        "segundoNombre": "Fernando",
        "primerApellido": "Pérez",
        "segundoApellido": "Ramírez",
        "cedula": "91234567",
        "correo": "raul.perez@example.com",
        "celular": "3909123456",
        "rol": "profesor",
        "estado": "activo"
    },
    {
        "codigo": 20,
        "primerNombre": "Elena",
        "segundoNombre": "Sofía",
        "primerApellido": "González",
        "segundoApellido": "Martínez",
        "cedula": "101234567",
        "correo": "elena.gonzalez@example.com",
        "celular": "3001012345",
        "rol": "auxiliar",
        "estado": "activo"
    }
]
